In [3]:
import matplotlib.pyplot as plot
import pandas as pds
import pylab as pl
import numpy as np
%matplotlib inline

In [5]:
df= pds.read_csv("FuelConsumptionCo2.csv")
df.head()

,MODELYEAR,MAKE,MODEL,VEHICLECLASS,ENGINESIZE,CYLINDERS,TRANSMISSION,FUELTYPE,FUELCONSUMPTION_CITY,FUELCONSUMPTION_HWY,FUELCONSUMPTION_COMB,FUELCONSUMPTION_COMB_MPG,CO2EMISSIONS
0,2014,ACURA,ILX,COMPACT,2.0,4,AS5,Z,9.9,6.7,8.5,33,196
1,2014,ACURA,ILX,COMPACT,2.4,4,M6,Z,11.2,7.7,9.6,29,221
2,2014,ACURA,ILX HYBRID,COMPACT,1.5,4,AV7,Z,6.0,5.8,5.9,48,136
3,2014,ACURA,MDX 4WD,SUV - SMALL,3.5,6,AS6,Z,12.7,9.1,11.1,25,255
4,2014,ACURA,RDX AWD,SUV - SMALL,3.5,6,AS6,Z,12.1,8.7,10.6,27,244

In [ ]:
df.describe()

In [6]:
cdf= df[['ENGINESIZE','CYLINDERS','FUELCONSUMPTION_COMB','CO2EMISSIONS']]
cdf.head(10)

   ENGINESIZE  CYLINDERS  FUELCONSUMPTION_COMB  CO2EMISSIONS
0         2.0          4                   8.5           196
1         2.4          4                   9.6           221
2         1.5          4                   5.9           136
3         3.5          6                  11.1           255
4         3.5          6                  10.6           244
5         3.5          6                  10.0           230
6         3.5          6                  10.1           232
7         3.7          6                  11.1           255
8         3.7          6                  11.6           267
9         2.4          4                   9.2           212

In [ ]:
#PLOTING
viz =df[['ENGINESIZE','CYLINDERS','FUELCONSUMPTION_COMB','CO2EMISSIONS']]
viz.hist()
plot.show()

In [ ]:
#PLOTING SCATTER
plot.scatter(df.FUELCONSUMPTION_COMB,df.CO2EMISSIONS,color="black")
plot.xlabel("Fuelconsumption")
plot.ylabel("CO2Emissions")
plot.title("FuelConsumption vs Co2Emission")
plot.show()

In [ ]:
#PLOTING SCATTER
plot.scatter(df.ENGINESIZE,df.CO2EMISSIONS,color="red")
plot.xlabel("Engine Size")
plot.ylabel("CO2Emissions")
plot.title("EngineSize vs Co2Emission")
plot.show()

In [7]:
#Train and TEST Data Set
#SPLIT INTO TRAIN AND TEST
msk = np.random.rand(len(df))<0.8
train = cdf[msk]
test = cdf[~msk]

In [ ]:
#TRAIN SET of TRAIN DATA (0.8)

plot.scatter(train.ENGINESIZE,train.CO2EMISSIONS, color="red")
plot.xlabel('Engine Size')
plot.ylabel('Co2Emissions')
plot.title('Engine Size vs Co2Emissions of Train DataSets')
plot.show()

In [8]:
#Modeling

from sklearn import linear_model
regr = linear_model.LinearRegression()
train_x = np.asanyarray(train[['ENGINESIZE']])
train_y = np.asanyarray(train[['CO2EMISSIONS']])
regr.fit (train_x,train_y)

print('Coefficients:',regr.coef_)
print('Intercept:',regr.intercept_)

Coefficients: [[38.83337337]]
Intercept: [126.5393269]

In [ ]:
plot.scatter(train.ENGINESIZE,train.CO2EMISSIONS,color='red')
plot.plot(train_x,regr.coef_*train_x+regr.intercept_,'-b')
plot.xlabel("Engine size")
plot.ylabel("Emission")
plot.title("FIT LINE of TRAINED DATASET")
plot.show()

In [11]:
#EVALUATION
from sklearn.metrics import r2_score

test_x=np.asanyarray(test[['ENGINESIZE']])
test_y=np.asanyarray(test[['CO2EMISSIONS']])
test_y_ = regr.predict(test_x)
# print(test_y_)
print("Mean Absolute Error (MAE): %.3f" % np.mean(np.absolute(test_y_-test_y)))
print("Residual sum of Squares - Mean Squared Error(MSE):%.2f"% np.mean((test_y_-test_y)**2))
a=r2_score(test_y_,test_y)
print("R2-Score: %.2f" % a)
print("Acheived %d Acuraccy"% (a*100))

[[270.22280836]
 [309.05618173]
 [204.20607364]
 [204.20607364]
 [243.03944701]
 [371.18957912]
 [289.63949505]
 [328.47286842]
 [289.63949505]
 [281.87282037]
 [204.20607364]
 [204.20607364]
 [204.20607364]
 [243.03944701]
 [243.03944701]
 [204.20607364]
 [243.03944701]
 [204.20607364]
 [243.03944701]
 [243.03944701]
 [243.03944701]
 [297.40616972]
 [297.40616972]
 [297.40616972]
 [243.03944701]
 [243.03944701]
 [297.40616972]
 [204.20607364]
 [243.03944701]
 [204.20607364]
 [204.20607364]
 [219.73942299]
 [266.33947103]
 [243.03944701]
 [243.03944701]
 [367.30624178]
 [367.30624178]
 [367.30624178]
 [266.33947103]
 [180.90604962]
 [219.73942299]
 [266.33947103]
 [332.35620575]
 [332.35620575]
 [359.53956711]
 [359.53956711]
 [204.20607364]
 [332.35620575]
 [196.43939896]
 [196.43939896]
 [332.35620575]
 [332.35620575]
 [266.33947103]
 [219.73942299]
 [266.33947103]
 [219.73942299]
 [219.73942299]
 [266.33947103]
 [266.33947103]
 [219.73942299]
 [219.73942299]
 [180.90604962]
 [180.90604962]
 [305.1728444 ]
 [305.1728444 ]
 [336.23954309]
 [336.23954309]
 [262.45613369]
 [188.67272429]
 [204.20607364]
 [336.23954309]
 [204.20607364]
 [262.45613369]
 [367.30624178]
 [270.22280836]
 [270.22280836]
 [270.22280836]
 [188.67272429]
 [188.67272429]
 [204.20607364]
 [204.20607364]
 [204.20607364]
 [223.62276032]
 [320.70619374]
 [262.45613369]
 [223.62276032]
 [293.52283239]
 [332.35620575]
 [332.35620575]
 [332.35620575]
 [332.35620575]
 [359.53956711]
 [293.52283239]
 [332.35620575]
 [367.30624178]
 [367.30624178]
 [219.73942299]
 [332.35620575]
 [367.30624178]
 [367.30624178]
 [332.35620575]
 [332.35620575]
 [332.35620575]
 [204.20607364]
 [196.43939896]
 [196.43939896]
 [262.45613369]
 [184.78938695]
 [184.78938695]
 [262.45613369]
 [262.45613369]
 [262.45613369]
 [188.67272429]
 [204.20607364]
 [188.67272429]
 [270.22280836]
 [270.22280836]
 [344.00621776]
 [320.70619374]
 [320.70619374]
 [320.70619374]
 [320.70619374]
 [320.70619374]
 [320.70619374]
 [219.73942299]
 [219.73942299]
 [266.33947103]
 [375.07291646]
 [219.73942299]
 [219.73942299]
 [204.20607364]
 [204.20607364]
 [219.73942299]
 [262.45613369]
 [219.73942299]
 [188.67272429]
 [204.20607364]
 [204.20607364]
 [219.73942299]
 [204.20607364]
 [378.9562538 ]
 [328.47286842]
 [320.70619374]
 [320.70619374]
 [320.70619374]
 [320.70619374]
 [243.03944701]
 [262.45613369]
 [262.45613369]
 [305.1728444 ]
 [223.62276032]
 [262.45613369]
 [262.45613369]
 [320.70619374]
 [262.45613369]
 [262.45613369]
 [336.23954309]
 [243.03944701]
 [223.62276032]
 [184.78938695]
 [204.20607364]
 [223.62276032]
 [223.62276032]
 [262.45613369]
 [309.05618173]
 [188.67272429]
 [188.67272429]
 [188.67272429]
 [188.67272429]
 [188.67272429]
 [188.67272429]
 [188.67272429]
 [204.20607364]
 [204.20607364]
 [173.13937494]
 [188.67272429]
 [262.45613369]
 [262.45613369]
 [262.45613369]
 [344.00621776]
 [188.67272429]
 [258.57279635]
 [258.57279635]
 [258.57279635]
 [258.57279635]
 [274.1061457 ]
 [274.1061457 ]
 [274.1061457 ]
 [231.389435  ]
 [312.93951907]
 [347.8895551 ]
 [266.33947103]
 [386.72292847]
 [177.02271228]
 [223.62276032]
 [223.62276032]
 [452.7396632 ]
 [204.20607364]
 [204.20607364]
 [266.33947103]
 [223.62276032]
 [204.20607364]
 [262.45613369]
 [262.45613369]
 [223.62276032]
 [196.43939896]
 [223.62276032]
 [281.87282037]
 [231.389435  ]
 [347.8895551 ]
 [196.43939896]
 [204.20607364]
 [223.62276032]
 [223.62276032]
 [204.20607364]
 [223.62276032]
 [204.20607364]
 [180.90604962]
 [223.62276032]
 [266.33947103]
 [250.80612168]]
Mean Absolute Error (MAE): 21.548
Residual sum of Squares - Mean Squared Error(MSE):826.54
R2-Score: 0.75
Acheived 74 Acuraccy

#